eng_word_lists = {
    'conjunctions': ['and', 'but', 'or', 'because', 'although', 'while', 'if', 'when', 'as', 'since', 'until',
                     'unless'],
    'pronouns': ['I', 'you', 'he', 'she', 'it', 'we', 'they', 'me', 'him', 'her', 'us', 'them', 'my', 'your', 'his',
                 'her', 'its', 'our', 'their', 'mine', 'yours', 'his', 'hers', 'ours', 'theirs', 'myself', 'yourself',
                 'himself', 'herself', 'itself', 'ourselves', 'yourselves', 'themselves', 'who', 'whom', 'whose',
                 'which', 'what', 'whatever', 'whoever', 'whichever', 'whomever'],
    'adverbs': ['quickly', 'slowly', 'often', 'never', 'very', 'well', 'always', 'sometimes', 'usually', 'now', 'then',
                'here', 'there', 'so', 'too', 'very', 'really', 'quite', 'almost', 'much', 'more', 'most', 'less',
                'least', 'together', 'apart', 'really', 'especially', 'nearly', 'just', 'even', 'almost',
                'really', 'too', 'enough', 'rather', 'hardly', 'scarcely', 'certainly', 'probably',
                'possibly', 'definitely', 'actually', 'finally', 'already', 'soon', 'recently', 'lately',
                'simply', 'easily', 'carefully', 'completely', 'properly', 'badly', 'poorly', 'loudly',
                'silently', 'anxiously', 'happily', 'sadly', 'gently', 'kindly', 'naturally',
                'honestly', 'suddenly', 'quietly', 'immediately', 'gradually'],
    'question': ['what', 'who', 'where', 'when', 'why', 'how', 'which', 'whom', 'whose', 'whichever', 'whatever',
                 'whoever', 'whenever', 'wherever', 'whyever', 'howsoever'],
    'verbs': ['be', 'have', 'do', 'say', 'get', 'make', 'go', 'know', 'take', 'see', 'come', 'think', 'look', 'want',
              'give', 'use', 'find', 'tell', 'ask', 'work', 'seem', 'feel', 'try', 'leave', 'call', 'show', 'ask',
              'try', 'need', 'feel', 'become', 'put', 'mean', 'keep', 'let', 'begin', 'seem', 'help', 'talk', 'turn',
              'start', 'show', 'hear', 'play', 'run', 'move', 'like', 'live', 'believe', 'hold', 'bring', 'happen',
              'write', 'provide', 'sit', 'stand', 'lose', 'pay', 'meet', 'include', 'continue', 'set', 'learn',
              'change', 'lead', 'understand', 'watch', 'follow', 'stop', 'create', 'speak', 'read', 'allow',
              'add', 'spend', 'grow', 'open', 'walk', 'win', 'offer', 'remember', 'love', 'consider', 'appear',
              'buy', 'wait', 'serve', 'send', 'expect', 'build', 'stay', 'fall', 'cut', 'reach', 'remain'],
    'numbers': ['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten'],
    'colors': ['red', 'blue', 'green', 'yellow', 'black', 'white', 'orange', 'purple', 'brown', 'pink', 'gray',
               'beige'],
    'animals': ['dog', 'cat', 'bird', 'elephant', 'lion', 'fish', 'horse', 'cow', 'tiger', 'rabbit', 'bear', 'sheep',
                'monkey', 'giraffe', 'snake', 'penguin', 'dolphin', 'kangaroo', 'zebra', 'panda', 'fox', 'deer', 'wolf',
                'turtle'],
    'time': ['day', 'night', 'morning', 'afternoon', 'evening', 'today', 'tomorrow', 'yesterday', 'week', 'month',
             'year', 'hour', 'minute', 'second', 'early', 'late', 'soon', 'now', 'still', 'ago',
             'recently', 'currently'],
    'family': ['mother', 'father', 'sister', 'brother', 'son', 'daughter', 'grandmother', 'grandfather', 'aunt',
               'uncle', 'cousin', 'niece', 'nephew', 'parents', 'siblings', 'children', 'grandparents',
               'relatives', 'family', 'in-laws'],
    'emotions': ['love', 'happiness', 'sadness', 'anger', 'fear', 'excitement', 'joy', 'surprise', 'calm',
                 'anxiety', 'disappointment', 'contentment', 'hope', 'relief', 'gratitude', 'embarrassment',
                 'envy', 'disgust', 'affection', 'resentment', 'proud', 'lonely', 'nervous', 'confident'],
    'foods': ['pizza', 'hamburger', 'apple', 'orange', 'banana', 'grapes', 'strawberries', 'ice cream', 'cake',
              'chocolate', 'sandwich', 'soup', 'pasta', 'rice', 'steak', 'chicken', 'fish', 'vegetables', 'salad',
              'bread', 'milk', 'coffee', 'tea', 'juice'],
    'transportation': ['car', 'bus', 'train', 'bicycle', 'motorcycle', 'subway', 'taxi', 'plane', 'boat', 'ship',
                       'truck', 'helicopter', 'bicycle', 'scooter', 'skateboard', 'walking', 'running', 'riding'],
    'objects': ['table', 'chair', 'bed', 'desk', 'lamp', 'bookshelf', 'couch', 'television', 'computer', 'phone',
                'pen', 'pencil', 'notebook', 'scissors', 'knife', 'spoon', 'fork', 'plate', 'cup', 'glass',
                'watch', 'umbrella', 'camera', 'bag', 'shoes'],
    'places': ['home', 'school', 'hospital', 'park', 'beach', 'restaurant', 'store', 'library', 'gym', 'office',
               'museum', 'cinema', 'bank', 'church', 'airport', 'train station', 'bus stop', 'city', 'town',
               'village', 'country', 'mountain', 'river', 'lake', 'ocean'],
    'people': ['friend', 'teacher', 'student', 'parent', 'child', 'sibling', 'boss', 'colleague', 'neighbor',
               'stranger', 'doctor', 'nurse', 'police officer', 'firefighter', 'artist', 'musician', 'actor',
               'writer', 'scientist', 'athlete', 'chef', 'politician', 'celebrity', 'customer']
}
